### ISSUE TITLE
It's not working in 0.15.4

### ISSUE THREAD

**Issue by WonyeopJeong** [EconomyS/EconomyLand#5]
after i use the command "/land pos1~pos2", when i say /land buy

console say like this:    

  at me.onebone.economyland.EconomyLand.addLand(EconomyLand.java 
      at me.onebone.economyland.EconomyLand.addLand(EconomyLand.java

```
  at me.onebone.economyland.EconomyLand.onCommand(EconomyLand.ja
```

10)
      at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:

```
  at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMa
```

va:165)
      at cn.nukkit.Server.dispatchCommand(Server.java:628)
      at cn.nukkit.Player.handleDataPacket(Player.java:2732)
      at cn.nukkit.network.Network.processPackets(Network.java:193)
      at cn.nukkit.network.Network.processBatch(Network.java:164)
      at cn.nukkit.Player.handleDataPacket(Player.java:1795)
      at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNet
rface.java:154)
      at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHa
r.java:123)
      at cn.nukkit.network.RakNetInterface.process(RakNetInterface.j
63)
      at cn.nukkit.network.Network.processInterfaces(Network.java:75
      at cn.nukkit.Server.tick(Server.java:980)
      at cn.nukkit.Server.tickProcessor(Server.java:781)
      at cn.nukkit.Server.start(Server.java:761)
      at cn.nukkit.Server.<init>(Server.java:455)
      at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by onebone** [comment]
Download from my jenkins server.
http://jenkins.onebone.me/job/EconomyLand/lastSuccessfulBuild/artifact/target/EconomyLand-1.0.0.jar
