### ISSUE TITLE
Options: Invalid pickup value

### ISSUE THREAD

**Issue by ghost** [EconomyS/EconomyLand#7]
When using this command [ /land option 0 pickup true/false ]
The console to brush out the following information
==========================
[CRITICAL] Exception while invoking run
java.lang.NullPointerException
        at me.onebone.economyland.EconomyLand.showBlocks(EconomyLand.java:972)
        at me.onebone.economyland.ShowBlockTask.onRun(ShowBlockTask.java:32)
        at cn.nukkit.scheduler.ServerScheduler.lambda$addTask$1(ServerScheduler.java:165)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:208)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:461)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
==========================
Whether it is true or false,the chest can't open
Hope to fix the problem
Thanks

**Comment by onebone** [comment]
Wasn't there any land creation at that time?

**Comment by ghost** [comment]
No,

**Comment by ghost** [comment]
Can you fix this problem?

**Comment by ghost** [comment]
:(
